#include "../common.h"
#include "../ast/ast_structs.h"
#include "typing.h"
void visit_program(AST_Program* pg,int bootstrap);
static void* visit_Program(AST_Program* node);
static void* visit_child_Program(AST_Program* node);
static void* visit_ExtDefList(AST_ExtDefList* node);
static void* visit_child_ExtDefList(AST_ExtDefList* node);
static void* visit_ExtDef(AST_ExtDef* node);
static void* visit_ExtDef_Var(AST_ExtDef_Var* node);
static void* visit_ExtDef_MayStruct(AST_ExtDef_MayStruct* node);
static void* visit_ExtDef_Fn(AST_ExtDef_Fn* node);
static void* visit_child_ExtDef_Var(AST_ExtDef_Var* node);
static void* visit_child_ExtDef_MayStruct(AST_ExtDef_MayStruct* node);
static void* visit_child_ExtDef_Fn(AST_ExtDef_Fn* node);
static void* visit_ExtDecList(AST_ExtDecList* node);
static void* visit_ExtDecList_0(AST_ExtDecList_0* node);
static void* visit_ExtDecList_1(AST_ExtDecList_1* node);
static void* visit_child_ExtDecList_0(AST_ExtDecList_0* node);
static void* visit_child_ExtDecList_1(AST_ExtDecList_1* node);
static type* visit_Specifier(AST_Specifier* node);
static type* visit_Specifier_Ty(AST_Specifier_Ty* node);
static type* visit_Specifier_Struct(AST_Specifier_Struct* node);
static type* visit_child_Specifier_Ty(AST_Specifier_Ty* node);
static type* visit_child_Specifier_Struct(AST_Specifier_Struct* node);
static type* visit_StructSpecifier(AST_StructSpecifier* node);
static type* visit_StructSpecifier_Ref(AST_StructSpecifier_Ref* node);
static type* visit_StructSpecifier_Def(AST_StructSpecifier_Def* node);
static void* visit_child_StructSpecifier_Ref(AST_StructSpecifier_Ref* node);
static type* visit_child_StructSpecifier_Def(AST_StructSpecifier_Def* node);
static char* visit_OptTag(AST_OptTag* node);
static void* visit_child_OptTag(AST_OptTag* node);
static char* visit_Tag(AST_Tag* node);
static void* visit_child_Tag(AST_Tag* node);
static struct vardec* visit_VarDec(AST_VarDec* node);
static struct vardec* visit_VarDec_Var(AST_VarDec_Var* node);
static struct vardec* visit_VarDec_Array(AST_VarDec_Array* node);
static struct vardec* visit_child_VarDec_Var(AST_VarDec_Var* node);
static struct vardec* visit_child_VarDec_Array(AST_VarDec_Array* node);
static void* visit_FunDec(AST_FunDec* node);
static void* visit_FunDec_HasArg(AST_FunDec_HasArg* node);
static void* visit_FunDec_NoArg(AST_FunDec_NoArg* node);
static void* visit_child_FunDec_HasArg(AST_FunDec_HasArg* node);
static void* visit_child_FunDec_NoArg(AST_FunDec_NoArg* node);
static void* visit_VarList(AST_VarList* node);
static void* visit_VarList_0(AST_VarList_0* node);
static void* visit_VarList_1(AST_VarList_1* node);
static void* visit_child_VarList_0(AST_VarList_0* node);
static void* visit_child_VarList_1(AST_VarList_1* node);
static void* visit_ParamDec(AST_ParamDec* node);
static struct vardec* visit_child_ParamDec(AST_ParamDec* node);
static void* visit_CompSt(AST_CompSt* node);
static void* visit_child_CompSt(AST_CompSt* node);
static void* visit_StmtList(AST_StmtList* node);
static void* visit_child_StmtList(AST_StmtList* node);
static void* visit_Stmt(AST_Stmt* node);
static void* visit_Stmt_Expr(AST_Stmt_Expr* node);
static void* visit_Stmt_Comp(AST_Stmt_Comp* node);
static void* visit_Stmt_Ret(AST_Stmt_Ret* node);
static void* visit_Stmt_If(AST_Stmt_If* node);
static void* visit_Stmt_Ife(AST_Stmt_Ife* node);
static void* visit_Stmt_While(AST_Stmt_While* node);
static void* visit_child_Stmt_Expr(AST_Stmt_Expr* node);
static void* visit_child_Stmt_Comp(AST_Stmt_Comp* node);
static void* visit_child_Stmt_Ret(AST_Stmt_Ret* node);
static void* visit_child_Stmt_If(AST_Stmt_If* node);
static void* visit_child_Stmt_Ife(AST_Stmt_Ife* node);
static void* visit_child_Stmt_While(AST_Stmt_While* node);
static void* visit_DefList(AST_DefList* node);
static void* visit_child_DefList(AST_DefList* node);
static void* visit_Def(AST_Def* node);
static void* visit_child_Def(AST_Def* node);
static void* visit_DecList(AST_DecList* node);
static void* visit_DecList_0(AST_DecList_0* node);
static void* visit_DecList_1(AST_DecList_1* node);
static void* visit_child_DecList_0(AST_DecList_0* node);
static void* visit_child_DecList_1(AST_DecList_1* node);
static void* visit_Dec(AST_Dec* node);
static void* visit_Dec_Simple(AST_Dec_Simple* node);
static void* visit_Dec_WithInit(AST_Dec_WithInit* node);
static void* visit_child_Dec_Simple(AST_Dec_Simple* node);
static void* visit_child_Dec_WithInit(AST_Dec_WithInit* node);
